id: av06
titulo: "Projeto Integrado — SQL + Python + Pandas + Matplotlib"
tipo: MP
prazo: 08/05/2026
prazo-label: "08/05 — durante a aula, dupla"
ucs:
  - UC05
  - UC08
  - UC09
  - UC03
trimestre: T1
indicadores:
  - UC08.5
  - UC05.4
  - UC09.9
  - UC09.10
  - UC03.5
status: concluida
